
project_name: aipower-test       #项目名称,必填
cluster_name: qh-gpu-st-01       #集群名称,必填
##
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: test-aipower3-yl2        #应用名，必填
  namespace: aipower-test-space  #命名空间，必填
  annotations:
    cpaas.io/user: [userinfo]  #为大禹自动填入发布人信息，必填项
spec:
  componentTemplates:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: test-aaa-yl                                               #configmap名称
      namespace: aipower-test-space                                         #应用部署的namespace
      annotations:
        resource.alauda.io/description: test-aaa-yl                   #configmap描述
    data:
      cfgs.yaml: |          #configmap key 对应镜像volumeMounts中的子路径，configmap value 为导入的nginx.conf文件
        common:
          temp_aws_access_key: li04idfuser
          temp_aws_secret_access_key: Wm/2WKrgh+zaNLVuifajtP9jLJhgMzIlEoSaSje2
          temp_bucket_name: LI04_00_PWCIMG.00
          temp_ecs_host: s3ecs.itcenter.cmbchina.cn
          temp_ecs_port: 9020
          gen_aws_access_key: lt23.03_user11
          gen_aws_secret_access_key: wFJcYrNqjCnNuRZ6u9wncIqadVnhSVbkEfiwRM3t
          gen_bucket_name: lt23.03_user11_bucket11
          gen_ecs_host: s3ecs.itcenter.cmbchina.cn
          gen_ecs_port: 9020
          diff_aws_access_key: li04idfuser
          diff_aws_secret_access_key: Wm/2WKrgh+zaNLVuifajtP9jLJhgMzIlEoSaSje2
          diff_bucket_name: LI04_00_PWCIDF.00
          diff_ecs_host: s3ecs.itcenter.cmbchina.cn
          diff_ecs_port: 9020
          tmsrs_aws_access_key: lz02.01-user1-prd
          tmsrs_aws_secret_access_key: x+Hc+18ahn5+QNNQpubbL/g7CoZ4BoyHxruLP36q
          tmsrs_bucket_name: lz02.01-yanyin2021-prd
          tmsrs_ecs_host: s3ecs.itcenter.cmbchina.cn
          tmsrs_ecs_port: 9020
          iv : 0000000000000000
          secret_key : Li04@pwc_yY2020!
          jar_ip : 10.253.3.74
  - kind: Secret
    apiVersion: v1
    metadata:
      name: test-secret-yl                                               #secret名称
      namespace: aipower-test-space                                         #应用部署的namespace
      annotations:
        resource.alauda.io/description: test-secret-yl                   #configmap描述
    labels: []
    data:
      test-configjson: |-
         cmVkaXM6Ly9oYXJib3ItYWlwb3dlci10ZXN0LWNoYXJ0LWhhcmJvci1oYXJib3ItcmVkaXM6NjM3OS81
      aa: MTIzNDU2Nzg=
    type: Opaque
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-aipower3-yl2-2048     #应用名+镜像名 格式为"应用名-镜像名"
      namespace: aipower-test-space   #命名空间名称
      labels: {}
    spec:
      replicas: 1
      selector:
        matchLabels:
          service.cpaas.io/name: deployment-test-aipower3-yl2-2048      #固定格式 为 degloyment+应用名+镜像名
          project.cpaas.io/name: aipower-test                          #项目名称
      template:
        metadata:
          labels:
            service.cpaas.io/name: deployment-test-aipower3-yl2-2048    #固定格式 为  degloyment+应用名+镜像名
            filemanager-injection: enabled
            project.cpaas.io/name: aipower-test                        #项目名称
            app.cpaas.io/name: test-aipower3-yl2.aipower-test-space     #固定格式 为  应用名+命名空间名称
          annotations:
            ovn.kubernetes.io/egress_rate: '10'                        #上行带宽，必填
            ovn.kubernetes.io/ingress_rate: '10'                       #下行带宽，必填
            devops-cluster: train                                    #release或train，必填，对应发布集群是否为在线还是预测
        spec:
          containers:                                                  #容器内容，必填
          - name: '2048'                                               #镜像名称
            image: [imageuri]                                          #镜像地址，必填,此参数为大禹自动填入流水线label
            resources:
              limits:                                                  #限制值，必填
                cpu: 100m
                memory: 256Mi
                tencent.com/vcuda-core: '10'                           #GPU算力 10为0.1整卡以上为100、200  非必填项，limit requests 一致
                tencent.com/vcuda-memory: '4'                          #GPU显存  每单位为256MB
              requests:                                                #请求值，必填
                cpu: 100m
                memory: 256Mi
                tencent.com/vcuda-core: '10'                            #GPU算力 10为0.1整卡以上为100、200  非必填项，limit requests 一致
                tencent.com/vcuda-memory: '4'                           #GPU显存  每单位为256MB
            ports: []
            volumeMounts:                                              #存储卷挂载路径,要和定义的Volumes名称一致，路径要精确文件命名，选填
            - mountPath: /data
              name: new-volume
              readOnly: false
            - mountPath: /ocr_servers/cfgs.yaml
              name: cm-volume
              readOnly: false
              subPath: cfgs.yaml
            - mountPath: /etc/test-configjson                          #完整的挂载目录以及文件挂载名
              name: secret-volume                                      #对应volumes的secret的name
              readOnly: false
              subPath: test-configjson                                  #为secret内文件名
            - mountPath: /etc/aa
              name: secret-volume
              readOnly: false
              subPath: aa
            env:                                                       ##设置环境变量,选填
            - name: name
              value: aipower3
            - name: age
              value: '18'
            - name: field
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            envFrom:                                                   #可以使用ConfigMap或secret来填充环境变量，选填
            - secretRef:
                name: test-secret
            lifecycle:                                                 #生命周期钩子，在容器结束前执行的命令或操作（postStart可以指定容器启动后立即执行操作），选填
              preStop:
                httpGet:
                  path: /
                  port: 80
                  scheme: HTTP
            livenessProbe:                                             #Pod存活探针,探测应用程序是否正在运行，选填
              httpGet:
                path: /
                port: 80
                scheme: HTTP
            readinessProbe:                                            #Pod可读性探针，探测容器是否已经就绪可以接收流量，选填
              httpGet:
                path: /
                port: 80
                scheme: HTTP
          affinity:                                                    #亲和性设置，在线集群必须满足反亲和策略
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:         #pod软亲和策略，尽量满足调度策略进行调度
              - weight: 1                                              #匹配权重设定，权重越高优先级越高
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.cpaas.io/name: test-aipower3.aipower-test-space  #应用名.命名空间名，必填
                  topologyKey: kubernetes.io/hostname                    #根据选择的拓扑域进行匹配，必填
          terminationGracePeriodSeconds: 30
          nodeSelector:                                               #指定调度节点带有label标记为kubernetes.io/hostname=node1，选填
            kubernetes.io/hostname: 55.13.75.13
          tolerations:                                                #对污点(Taint)的容忍声明，其中的key、value、effect 与Node的Taint设置需保持一致，选填
          - effect: NoSchedule
            key: galaxy
            operator: Equal
            value: ''
          volumes:                                                     #声明的存储卷，选填
          - name: new-volume
            persistentVolumeClaim:
              claimName: file01-yl
          - name: cm-volume
            configMap:
              name: test-aaa-yl
              items:
                - key: cfgs.yaml
                  path: cfgs.yaml
          - name: secret-volume
            secret:
              secretName: test-secret-yl                                #要挂载的secret名称
#################  以下为路由和访问规则为非必填项
  - apiVersion: v1
    kind: Service
    metadata:
      name: svc-test-aipower3-yl2                        #service名字 建议为svc+应用名
      namespace: aipower-test-space                     #命名空间名称
    spec:
      type: ClusterIP
      sessionAffinity: None
      ports:
      - name: tcp-80-80                                 #命名规范为tcp + service_port + pod_port
        protocol: TCP
        port: 80                                        #service暴露端口，与下面ingress 填写的端口一致
        targetPort: 80                                  #容器对外暴露端口
      selector:
        project.cpaas.io/name: aipower-test                           #项目名称
        service.cpaas.io/name: deployment-test-aipower3-yl2-2048
#################  以下为路由和访问规则为非必填项
  - apiVersion: extensions/v1beta1
    kind: Ingress                                                  #ingress名字，建议格式为ing+应用名
    metadata:
      name: ing-test-aipower3-yl2
      namespace: aipower-test-space
      annotations:
        kubernetes.io/ingress.class: ''
        alb.networking.cpaas.io/tls: ''
    spec:
      tls: []
      rules:
      - host: test-yl2-aipower3.qh.aipower3.cmbchina.cn             #指定访问的访问域名，必填项
        http:
          paths:
          - path: '/'                                           #访问的路径
            backend:
              serviceName: svc-test-aipower3-yl2                    #service应用名称，对应上面service名字
              servicePort: 80                                      #服务端口，对应上面service暴露端口
